### ISSUE TITLE
Build server

### ISSUE THREAD

**Issue by dsernst** [Boundless-Avocado/Boundless-Avocado#1]
We need a base server that stores the database of users and groups, and connects to the various interfaces (web client, Twilio SMS, email?)

**Comment by dsernst** [comment]
---

This issue has been cloned in from the old private repository.

---

**Comment by dsernst** [comment]
If the server has a REST interface, the different clients can just send it HTTP requests! Platform agnostic.

Sound good, @all ?

**Comment by p3tuh** [comment]
sounds good, the simpler the better.

**Comment by dsernst** [comment]
As of d39ff80e0f2dfc1fb753a7d487ed8f7d9ebdb7b6 the server handles:

POST /api/users/
GET /api/groups/
POST /api/groups/
POST /api/groups/:group/

**Comment by dsernst** [comment]
As of d2680ea, the server also handles:

GET /api/groups/:group/ to list all members

GET /api/groups/:group/pings to see history of pings
POST /api/groups/:group/pings to add a record of ping (not yet integrated with outgoing notifications)

**Comment by dsernst** [comment]
Closing this for now. See https://github.com/Boundless-Avocado/Boundless-Avocado/wiki/REST-API for a description of the REST API
