### ISSUE TITLE
SMS Interface

### ISSUE THREAD

**Issue by dsernst** [Boundless-Avocado/Boundless-Avocado#3]
To make the product very lightweight, it would be especially handy to allow the user to use it all over SMS.

Twilio has JavaScript libraries to do this programmatically.

We can probably start with a free trial. Mike also has $12 in an account that is good for 1600 messages.

**Comment by dsernst** [comment]
---

This issue has been cloned in from the old private repository.

---

**Comment by dsernst** [comment]
@p3tuh says in private chat:

> Mandrill has a text service as well with 1,000 free texts if we are developing with node according to the Lightning talk. In case twilio doesn't work out for any reason

**Comment by dsernst** [comment]
It's awesome that we have the great Twilio account with nearly $100 worth of credit. Perfect for MVP!

And if we want a more affordable long-term option down the road, [Plivo](https://www.plivo.com/), a competitor, just announced major price drops:
- free incoming SMS
- $0.004 per outgoing from a shortcode, $0.0035 from a local number

Plivo blog: [Free Incoming SMS for All US Short Codes and 46% Price Drop in Outbound](https://www.plivo.com/blog/free-incoming-sms-for-all-us-short-codes-and-outbound-price-drop/)

![Plivo deal](https://s3.amazonaws.com/plivo_blog_uploads/static_assets/images/blog/short-code-price-drop-banner.png)

For comparison, here's Twilio:

![Twilio pricing](https://cloud.githubusercontent.com/assets/6340841/5953552/565a442e-a740-11e4-86e2-cf0e1f265248.png)

**Comment by p3tuh** [comment]
Nice!

Best,

Peter Kim
510.604.7443
chong.peter.kim@gmail.com

**Comment by dsernst** [comment]
Closing for now, as we were able to get this all to work with Twilio. See https://github.com/Boundless-Avocado/Boundless-Avocado/wiki/Client-Commands for a list of commands
