### ISSUE TITLE
Web interface

### ISSUE THREAD

**Issue by dsernst** [Boundless-Avocado/Boundless-Avocado#4]
To get started the simplest way to interact with the backend would probably be to use a web-based desktop interface.

**Comment by dsernst** [comment]
---

This issue has been cloned in from the old private repository.

---

**Comment by p3tuh** [comment]
TODO : 
1. ~~create a new group page~~
2. ~~pass username to server when joining a group~~
3. ~~fix the weird redirect to index after joining a group~~
4. ~~check user inputs for validity~~ very rudimentary for now

**Comment by p3tuh** [comment]
1. Pinging members of group... TBD

**Comment by dsernst** [comment]
Pinging groups works!
