### ISSUE TITLE
Guac.io expires February 7

### ISSUE THREAD

**Issue by dsernst** [Boundless-Avocado/Boundless-Avocado#68]
@Boundless-Avocado/owners  @Boundless-Avocado/aberrant-marble @Boundless-Avocado/wicked-babies 

![image](https://cloud.githubusercontent.com/assets/6340841/12189864/d3e30a4e-b576-11e5-97f6-4b4d93a60e28.png)

:cry:

**Comment by dsernst** [comment]
> guac.io expires in 14 days

**Comment by eds101** [comment]
apply to ycomb now!!

**Comment by dsernst** [comment]
All 10 of us?

**Comment by rmi22186** [comment]
11 heads are better than 2

**Comment by eds101** [comment]
Hell yeah

**Comment by dsernst** [comment]
Renewed

![image](https://cloud.githubusercontent.com/assets/6340841/12871443/6b6d2400-cd30-11e5-8c13-bc3bcde3e88c.png)

**Comment by eds101** [comment]
are you on venmo?

**Comment by dsernst** [comment]
Yep

On Sunday, February 7, 2016, Eric Schmidt notifications@github.com wrote:

> are you on venmo?
> On Sun, Feb 7, 2016 at 12:19 AM David Ernst <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
> 
> > Renewed
> > 
> > [image: image]
> > <
> > https://cloud.githubusercontent.com/assets/6340841/12871443/6b6d2400-cd30-11e5-8c13-bc3bcde3e88c.png
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/Boundless-Avocado/Boundless-Avocado/issues/68#issuecomment-180974572
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Boundless-Avocado/Boundless-Avocado/issues/68#issuecomment-181138305
> .

## 

## 

David Ernst
